image: python 2.7

before_script:
    - virtualenv env
    - source env/bin/activate
    - pip install --upgrade pip
    - pip install flake8
    - pip install -r requirements.txt

stages:
    - build 
    - test

build:
    stage: build
    cache:
        paths:
              - venv/
    script:
        - source venv/bin/activate
        - python setup.py install

test:
    stage: test
    cache:
        paths:
              - venv/
    script:
        - source venv/bin/activate
        - python setup.py test

