image: python 2.7

stages:
    - build 
    #- test
    
build:
    stage: build
    script:
        - pip install --upgrade pip
        - pip install flake8
        - pip install -r requirements.txt
        - sudo python setup.py install

    