image: python 2.7

cache:
  untracked: true

stages:
  - build
  - test


build_job:
  stage: build
  script:
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install flake8
    - pip install -r requirements.txt
    - flake8
    - python setup.py install -t


test_job:
  stage: test
  script:
    - source venv/bin/activate
    - python setup.py test
