image: python 2.7

cache:
  paths:
  - venv/

stages:
  - build
  - test

before_script:
  - virtualenv venv
  - source venv/bin/activate

build_job:
  stage: build
  script:
  - pip install --upgrade pip
  - pip install flake8
  - pip install -r requirements.txt
  - python setup.py install -t


test_job:
  stage: test
  script:
    - python setup.py test
