image: "registry.gitlab.cc-asp.fraunhofer.de:4567/force/osp-core"

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - python3 setup.py install -t
    - flake8 --exclude=cuds/classes/generated,venv,venv3,build --ignore=F401,F403,E402


test_job:
  stage: test
  script:
    - python3 setup.py test



#image: python 3.6

#cache:
#  untracked: true

#stages:
#  - build
#  - test


#build_job:
#  stage: build
#  script:
#    - python3 -m venv venv3
#    - source venv3/bin/activate
#    - pip3 install --upgrade pip
#    - pip3 install flake8
#    - pip3 install -r requirements.txt
#    - python3 setup.py install -t
#    - flake8 --exclude=cuds/classes/generated,venv,venv3,build --ignore=F401,F403,E402


#test_job:
#  stage: test
#  script:
#    - source venv3/bin/activate
#    - python3 setup.py test
