image: python 2.7

before_script:
    
    - virtualenv env
    - source env/bin/activate
    - pip install --upgrade pip
    - pip install flake8
    - pip install -r requirements.txt

stages:
    - build 

build:
    stage: build
   
    script:
        - source env/bin/activate
        - python setup.py install -t
        - python setup.py test

