image: python 2.7

stages:
    - build 
    #- test
    
cache:
    stage: build
    directories:
        - "$HOME/.cache"
        - "$HOME/.ccache"
before_install:
    stage: build
        - ccache -s
        - export PATH=/usr/lib/ccache:${PATH}



build:
    stage: build
    script:
        - pip install --upgrade pip
        - pip install flake8
        - pip install -r requirements.txt
        - python setup.py install
