image: python 2.7

stages:
    - build 
    - test

build:
    stage: build
    cache:
        paths:
              - venv/
    script:
        - virtualenv venv
        - source venv/bin/activate
        - pip install --upgrade pip
        - pip install flake8
        - pip install -r requirements.txt
        - python setup.py install

test:
    stage: test
    cache:
        paths:
              - venv/
    script:
        - virtualenv venv
        - source venv/bin/activate
        - python setup.py test
