image: python 2.7
    
stages:
    - build 
    - test
    
build:
    stage: build
    script:
        - pip install --upgrade pip
        - pip install flake8

        
test:
    stage: test
    script:
        - pip install -r dev_requirements.txt
        - flake8 .
        - mkdir _test
        - pushd _test
        - py.test -v --pyargs simphony
