name: CI

on: pull_request

jobs:
  code_analysis:
    runs-on: self-hosted
    needs: cleanup
    steps:
      - uses: actions/checkout@v2

      - name: Flake8
        run: flake8 . --exclude=*/__init__.py,osp/core/ontology/docs/EMMO/* --ignore=W503

      - name: Radon
        run: |
          radon cc -s -a .,
          radon mi -s .
        
      - name: bandit
        run: bandit -r osp --skip B101
  
  test:
    runs-on: self-hosted
    needs: cleanup
    steps:
      - uses: actions/checkout@v2
      - name: unittesting
        run: tox

  cleanup:
    runs-on: self-hosted
    steps:
      - name: cleanup
      - run: rm -rf app/_work/osp-core-migration/osp-core-migration/*
